config/routes.rb
Diagnostic::Application.routes.draw do
  resources :test_names

  resources :test_titles

  resources :departments

  resources :entitle_discount_details

  resources :entitle_incentive_details

  resources :entitle_discounts

  resources :entitle_incentives

  devise_for :users

  get "home/index"

   match 'home/reference_categories' => 'home#reference_categories'
   match '/entitles_incentive_detail/:id' => 'home#entitles_incentive_detail',:via => [:get, :post]
   match '/entitles_discount_detail/:id' => 'home#entitles_discount_detail',:via => [:get, :post]

   root :to => 'home#index'

end

app/models/entitle_discount.rb
class EntitleDiscount < ActiveRecord::Base
  attr_accessible :ref_code, :ref_type

  has_many :entitle_discount_details


end

app/controllers/entitle_discounts_controller.rb
class EntitleDiscountsController < ApplicationController
  before_filter :set_entitle_discount, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @entitle_discounts = EntitleDiscount.all
    respond_with(@entitle_discounts)
  end

  def show
    respond_with(@entitle_discount)
  end

  def new
    @entitle_discount = EntitleDiscount.new
    respond_with(@entitle_discount)
  end

  def edit
  end

  def create
    @entitle_discount = EntitleDiscount.new(params[:entitle_discount])
    @entitle_discount.save
    respond_with(@entitle_discount)
  end

  def update
    @entitle_discount.update_attributes(params[:entitle_discount])
    respond_with(@entitle_discount)
  end

  def destroy
    @entitle_discount.destroy
    respond_with(@entitle_discount)
  end

  private
    def set_entitle_discount
      @entitle_discount = EntitleDiscount.find(params[:id])
    end
end

app/helpers/entitle_discounts_helper.rb
module EntitleDiscountsHelper
end

app/views/entitle_discounts/_form.html.erb
<%= form_for(@entitle_discount) do |f| %>
  <% if @entitle_discount.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entitle_discount.errors.count, "error") %> prohibited this entitle_discount from being saved:</h2>

      <ul>
      <% @entitle_discount.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ref_type %><br />
    <%= f.text_field :ref_type %>
  </div>
  <div class="field">
    <%= f.label :ref_code %><br />
    <%= f.text_field :ref_code %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entitle_discounts/edit.html.erb
<h1>Editing entitle_discount</h1>

<%= render 'form' %>

<%= link_to 'Show', @entitle_discount %> |
<%= link_to 'Back', entitle_discounts_path %>

app/views/entitle_discounts/index.html.erb
<h1>Listing entitle_discounts</h1>

<table>
  <tr>
    <th>Ref type</th>
    <th>Ref code</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @entitle_discounts.each do |entitle_discount| %>
  <tr>
    <td><%= entitle_discount.ref_type %></td>
    <td><%= entitle_discount.ref_code %></td>
    <td><%= link_to 'Show', entitle_discount %></td>
    <td><%= link_to 'Edit', edit_entitle_discount_path(entitle_discount) %></td>
    <td><%= link_to 'Destroy', entitle_discount, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Entitle discount', new_entitle_discount_path %>

app/views/entitle_discounts/new.html.erb
<h1>New entitle_discount</h1>

<%= render 'form' %>

<%= link_to 'Back', entitle_discounts_path %>

app/views/entitle_discounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Ref type:</b>
  <%= @entitle_discount.ref_type %>
</p>

<p>
  <b>Ref code:</b>
  <%= @entitle_discount.ref_code %>
</p>


<%= link_to 'Edit', edit_entitle_discount_path(@entitle_discount) %> |
<%= link_to 'Back', entitle_discounts_path %>