config/routes.rb
Diagnostic::Application.routes.draw do
  resources :test_names

  resources :test_titles

  resources :departments

  resources :entitle_discount_details

  resources :entitle_incentive_details

  resources :entitle_discounts

  resources :entitle_incentives

  devise_for :users

  get "home/index"

   match 'home/reference_categories' => 'home#reference_categories'
   match '/entitles_incentive_detail/:id' => 'home#entitles_incentive_detail',:via => [:get, :post]
   match '/entitles_discount_detail/:id' => 'home#entitles_discount_detail',:via => [:get, :post]

   root :to => 'home#index'

end

app/models/department.rb
class Department < ActiveRecord::Base
  attr_accessible :dep_type, :department_code, :name

  has_many :test_titles
end

app/models/entitle_discount.rb
class EntitleDiscount < ActiveRecord::Base
  attr_accessible :ref_code, :ref_type

  has_many :entitle_discount_details


end

app/models/entitle_discount_detail.rb
class EntitleDiscountDetail < ActiveRecord::Base
  attr_accessible :address, :contact_no, :contact_person, :dept, :designation, :dob, :entitle_discount_id, :name, :rate, :ref_code, :specialize, :tax_pan

  belongs_to :entitle_discount

  after_create :save_ref_code

  def save_ref_code
   puts "!!!!"
   
   if self.entitle_discount.ref_type == "Medicine Store"
    @a = Time.now
    @a = SecureRandom.urlsafe_base64(3)
    @code = "MED010" + @a
   end
   
   self.update_attribute(:ref_code,@code)
  end
end

app/models/entitle_incentive.rb
class EntitleIncentive < ActiveRecord::Base
  attr_accessible :ref_type,:ref_code

  has_many :entitle_incentive_details

  after_create :save_ref_code

  def save_ref_code
   
   @a = Time.now
   @a = SecureRandom.urlsafe_base64(7)
 
   self.update_attribute(:ref_code,@a)
  end
end

app/models/entitle_incentive_detail.rb
class EntitleIncentiveDetail < ActiveRecord::Base
  attr_accessible :address, :contact_no, :contact_person, :dept, :designation, :dob, :entitle_incentive_id, :name, :rate, :ref_code, :specialize, :tax_pan

  belongs_to :entitle_incentive

  after_create :save_ref_code

  def save_ref_code
   puts "!!!!"
   
   if self.entitle_incentive.ref_type == "Doctor"
    @a = Time.now
    @a = SecureRandom.urlsafe_base64(3)
    @code = "DR001" + @a
   end
   
   self.update_attribute(:ref_code,@code)
  end
end

app/models/test_name.rb
class TestName < ActiveRecord::Base
  attr_accessible :bio_ref, :element, :mth_tec, :name, :result, :test_title_id, :unit_mea

  belongs_to :test_title
end

app/models/test_title.rb
class TestTitle < ActiveRecord::Base
  attr_accessible :department_id, :description, :price, :process, :remarks, :restriction, :social_note, :tat, :title

  belongs_to :department
  has_many :test_names
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,:name,:is_admin
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout 'cerulean'
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_filter :set_department, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @department_labs = Department.where(:dep_type=>"Lab")
    @department_imo = Department.where(:dep_type=>"ImO")
  end

  def show
    respond_with(@department)
  end

  def new
    @department = Department.new
    respond_with(@department)
  end

  def edit
  end

  def create
    @department = Department.new(params[:department])
    if params[:department][:dep_type] == "Lab"
     @a = Time.now
     @a = SecureRandom.urlsafe_base64(3)
     @code = params[:department][:dep_type] + @a 
     @department.department_code = @code
    else
     @a = Time.now
     @a = SecureRandom.urlsafe_base64(3)
     @code = params[:department][:dep_type] + @a 
     @department.department_code = @code
    end
    @department.save
    respond_with(@department)
  end

  def update
    @department.update_attributes(params[:department])
    respond_with(@department)
  end

  def destroy
    @department.destroy
    respond_with(@department)
  end

  private
    def set_department
      @department = Department.find(params[:id])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
 
  def reference_categories
   @entitle_incentives = EntitleIncentive.all
   @entitle_discounts = EntitleDiscount.all
  end

 def entitles_incentive_detail
 	@entitle_incentive_details = EntitleIncentiveDetail.all
 end
 
 def entitles_discount_detail
 	@entitle_discount_details = EntitleDiscountDetail.all
 end

end

app/controllers/test_names_controller.rb
class TestNamesController < ApplicationController
  before_filter :set_test_name, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    
    @test_title = TestTitle.where(:id=>params[:test_title_id]).first
    respond_with(@test_names)
  end

  def show
    respond_with(@test_name)
  end

  def new
    @test_name = TestName.new
    respond_with(@test_name)
  end

  def edit
  end

  def create
    puts "!!!!!!!!!!!!!!!!!!!!!!!!!!"
    p params
    params[:name].each_with_index do |n,i|
      p params[:element]["#{i}"]
     @test_name = TestName.new
     @test_name.test_title_id = params[:test_name][:test_title_id]
     @test_name.name = n[1]
     @test_name.element = params[:element]["#{i}"]
     @test_name.bio_ref = params[:bio_ref]["#{i}"]
     @test_name.unit_mea = params[:unit]["#{i}"]
     @test_name.mth_tec = params[:mth]["#{i}"]
     @test_name.result = params[:result]["#{i}"]
     @test_name.save
    end

    #@test_name = TestName.new(params[:test_name])

    @test_name.save
    respond_with(@test_name)
  end

  def update
    @test_name.update_attributes(params[:test_name])
    respond_with(@test_name)
  end

  def destroy
    @test_name.destroy
    respond_with(@test_name)
  end

  private
    def set_test_name
      @test_name = TestName.find(params[:id])
    end
end

app/controllers/test_titles_controller.rb
class TestTitlesController < ApplicationController
  before_filter :set_test_title, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @dpt = Department.where(:id=>params[:dep_id]).first
    puts "!!!!!"
    p @dpt

    @test_titles = @dpt.test_titles
    respond_with(@test_titles)
  end

  def show
    respond_with(@test_title)
  end

  def new
    @test_title = TestTitle.new
    respond_with(@test_title)
  end

  def edit
  end

  def create
    @test_title = TestTitle.new(params[:test_title])
    @a = Time.now
    @a = SecureRandom.urlsafe_base64(7)
    @test_title.test_title_code = @a
    @test_title.save
    respond_with(@test_title)
  end

  def update
    @test_title.update_attributes(params[:test_title])
    respond_with(@test_title)
  end

  def destroy
    @test_title.destroy
    respond_with(@test_title)
  end

  private
    def set_test_title
      @test_title = TestTitle.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
 include BootstrapFlashHelper
end

app/helpers/bootstrap_flash_helper.rb
module BootstrapFlashHelper
  ALERT_TYPES = [:success, :info, :warning, :danger] unless const_defined?(:ALERT_TYPES)

  def bootstrap_flash(options = {})
    flash_messages = []
    flash.each do |type, message|
      # Skip empty messages, e.g. for devise messages set to nothing in a locale file.
      next if message.blank?

      type = type.to_sym
      type = :success if type == :notice
      type = :danger  if type == :alert
      type = :danger  if type == :error
      next unless ALERT_TYPES.include?(type)

      Array(message).each do |msg|
        text = content_tag(:div,
                           content_tag(:button, raw("&times;"), :class => "close", "data-dismiss" => "alert") +
                           msg.html_safe, :class => "alert fade in alert-#{type} #{options[:class]}")
        flash_messages << text if msg
      end
    end
    flash_messages.join("\n").html_safe
  end
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/entitle_discount_details_helper.rb
module EntitleDiscountDetailsHelper
end

app/helpers/entitle_discounts_helper.rb
module EntitleDiscountsHelper
end

app/helpers/entitle_incentives_helper.rb
module EntitleIncentivesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/test_names_helper.rb
module TestNamesHelper
end

app/helpers/test_titles_helper.rb
module TestTitlesHelper
end

app/views/home/entitles_discount_detail.html.erb
<script>
$(function() {    
    $('#entitled_discount_detail').dataTable();
});
</script>


<h2>Entitled Discount Details <a href="/entitle_discount_details/new?ref_type_id=<%=params[:id]%>"><button type="button" class="btn btn-link" style="float:right">Add Reference Detail</button></a></h2>

<table id="entitled_discount_detail" class="table table-striped table-bordered">
 <thead>   
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Contact no</th>
    <th>Tax pan</th>
    <th>Specialize</th>
    <th>Contact person</th>
    <th>Dept</th>
    <th>Designation</th>
    <th>Rate</th>
    <th>Ref code</th>
    <th>Actions</th>
    
  </tr>
</thead>
<tbody>
<%if @entitle_discount_details.present?%>
<% @entitle_discount_details.each do |entitle_discount_detail| %>
  <tr>
    <td><%= entitle_discount_detail.name %></td>
    <td><%= entitle_discount_detail.address %></td>
    <td><%= entitle_discount_detail.contact_no %></td>
    <td><%= entitle_discount_detail.tax_pan %></td>
    <td><%= entitle_discount_detail.specialize %></td>
    <td><%= entitle_discount_detail.contact_person %></td>
    <td><%= entitle_discount_detail.dept %></td>
    <td><%= entitle_discount_detail.designation %></td>
    <td><%= entitle_discount_detail.rate %></td>
    <td><%= entitle_discount_detail.ref_code %></td>
    
    <td><%#= link_to 'Show', entitle_incentive_detail %><%= link_to 'Edit', edit_entitle_discount_detail_path(entitle_discount_detail) %><%= link_to 'Destroy', entitle_discount_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
   
   
  </tr>
<% end %>
<%else%>
 <tr>
<td colspan="11" style="text-align:center">No Entitled Discount Details Found!</td>
</tr>
<%end%>
</tbody>
</table>

app/views/home/entitles_incentive_detail.html.erb
<script>
$(function() {    
    $('#entitled_commision_detail').dataTable();
});
</script>


<h2>Entitled Incentive/Comission Details <a href="/entitle_incentive_details/new?ref_type_id=<%=params[:id]%>"><button type="button" class="btn btn-link" style="float:right">Add Reference Detail</button></a></h2>

<table id="entitled_commision_detail" class="table table-striped table-bordered">
 <thead>   
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Contact no</th>
    <th>Tax pan</th>
    <th>Specialize</th>
    <th>Contact person</th>
    <th>Dept</th>
    <th>Designation</th>
    <th>Rate</th>
    <th>Ref code</th>
    <th>Actions</th>
    
  </tr>
</thead>
<tbody>
<%if @entitle_incentive_details.present?%>
<% @entitle_incentive_details.each do |entitle_incentive_detail| %>
  <tr>
    <td><%= entitle_incentive_detail.name %></td>
    <td><%= entitle_incentive_detail.address %></td>
    <td><%= entitle_incentive_detail.contact_no %></td>
    <td><%= entitle_incentive_detail.tax_pan %></td>
    <td><%= entitle_incentive_detail.specialize %></td>
    <td><%= entitle_incentive_detail.contact_person %></td>
    <td><%= entitle_incentive_detail.dept %></td>
    <td><%= entitle_incentive_detail.designation %></td>
    <td><%= entitle_incentive_detail.rate %></td>
    <td><%= entitle_incentive_detail.ref_code %></td>
    
    <td><%#= link_to 'Show', entitle_incentive_detail %><%= link_to 'Edit', edit_entitle_incentive_detail_path(entitle_incentive_detail) %><%= link_to 'Destroy', entitle_incentive_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
   
   
  </tr>
<% end %>
<%else%>
 <tr>
<td colspan="11" style="text-align:center">No Entitled Incentive/Comission Details Found!</td>
</tr>
<%end%>
</tbody>
</table>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/home/reference_categories.html.erb
<script>
$(function() {    
    $('#entitled_commision').dataTable();
});
</script>

<h2>Entitled Incentives/Commision Type</h2>

<table id="entitled_commision" class="table table-striped table-bordered">

 <thead>
    <tr>      
      <th> Reference Type </th>
     <th> Reference Code </th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
<% @entitle_incentives.each do |entitle_incentive| %>
  <tr>
    <td><%= link_to entitle_incentive.ref_type,"/entitles_incentive_detail/#{entitle_incentive.id}" %></td>
      <td><%= entitle_incentive.ref_code %></td>
    <td><%= link_to 'Edit', edit_entitle_incentive_path(entitle_incentive) %><%= link_to 'Destroy', entitle_incentive, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</tbody>
</table>


<h2>Entitled Discounts Type</h2>

<table id="entitled_dis" class="table table-striped table-bordered">

 <thead>
    <tr>      
      <th> Reference Type </th>
     <th> Reference Code </th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
<% @entitle_discounts.each do |entitle_discount| %>
  <tr>
    <td><%= link_to entitle_discount.ref_type,"/entitles_discount_detail/#{entitle_discount.id}" %></td>
    <td><%= entitle_discount.ref_code %></td>
    
    <td><%= link_to 'Edit', edit_entitle_discount_path(entitle_discount) %><%= link_to 'Destroy', entitle_discount, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    
  </tr>
<% end %>
</tbody>
</table>