config/routes.rb
Diagnostic::Application.routes.draw do
  resources :test_names

  resources :test_titles

  resources :departments

  resources :entitle_discount_details

  resources :entitle_incentive_details

  resources :entitle_discounts

  resources :entitle_incentives

  devise_for :users

  get "home/index"

   match 'home/reference_categories' => 'home#reference_categories'
   match '/entitles_incentive_detail/:id' => 'home#entitles_incentive_detail',:via => [:get, :post]
   match '/entitles_discount_detail/:id' => 'home#entitles_discount_detail',:via => [:get, :post]

   root :to => 'home#index'

end

app/models/entitle_incentive.rb
class EntitleIncentive < ActiveRecord::Base
  attr_accessible :ref_type,:ref_code

  has_many :entitle_incentive_details

  after_create :save_ref_code

  def save_ref_code
   
   @a = Time.now
   @a = SecureRandom.urlsafe_base64(7)
 
   self.update_attribute(:ref_code,@a)
  end
end

app/controllers/entitle_incentives_controller.rb
class EntitleIncentivesController < ApplicationController
  before_filter :set_entitle_incentive, only: [:show, :edit, :update, :destroy]
  require 'securerandom'

  respond_to :html

  def index
    @entitle_incentives = EntitleIncentive.all
    respond_with(@entitle_incentives)
  end

  def show
    respond_with(@entitle_incentive)
  end

  def new
    @entitle_incentive = EntitleIncentive.new
    respond_with(@entitle_incentive)
  end

  def edit
  end

  def create
    @entitle_incentive = EntitleIncentive.new(params[:entitle_incentive])
    
    @entitle_incentive.save
    respond_with(@entitle_incentive)
  end

  def update
    @entitle_incentive.update_attributes(params[:entitle_incentive])
    respond_with(@entitle_incentive)
  end

  def destroy
    @entitle_incentive.destroy
    respond_with(@entitle_incentive)
  end

  private
    def set_entitle_incentive
      @entitle_incentive = EntitleIncentive.find(params[:id])
    end
end

app/helpers/entitle_incentives_helper.rb
module EntitleIncentivesHelper
end

app/views/entitle_incentives/_form.html.erb
<%= form_for(@entitle_incentive) do |f| %>
  <% if @entitle_incentive.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entitle_incentive.errors.count, "error") %> prohibited this entitle_incentive from being saved:</h2>

      <ul>
      <% @entitle_incentive.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ref_type %><br />
    <%= f.text_field :ref_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entitle_incentives/edit.html.erb
<h1>Editing entitle_incentive</h1>

<%= render 'form' %>

<%= link_to 'Show', @entitle_incentive %> |
<%= link_to 'Back', entitle_incentives_path %>

app/views/entitle_incentives/index.html.erb
<h1>Listing entitle_incentives</h1>

<table>
  <tr>
    <th>Ref type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @entitle_incentives.each do |entitle_incentive| %>
  <tr>
    <td><%= entitle_incentive.ref_type %></td>
    <td><%= link_to 'Show', entitle_incentive %></td>
    <td><%= link_to 'Edit', edit_entitle_incentive_path(entitle_incentive) %></td>
    <td><%= link_to 'Destroy', entitle_incentive, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Entitle incentive', new_entitle_incentive_path %>

app/views/entitle_incentives/new.html.erb
<h1>New entitle_incentive</h1>

<%= render 'form' %>

<%= link_to 'Back', entitle_incentives_path %>

app/views/entitle_incentives/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Ref type:</b>
  <%= @entitle_incentive.ref_type %>
</p>


<%= link_to 'Edit', edit_entitle_incentive_path(@entitle_incentive) %> |
<%= link_to 'Back', entitle_incentives_path %>