config/routes.rb
Diagnostic::Application.routes.draw do
  resources :test_names

  resources :test_titles

  resources :departments

  resources :entitle_discount_details

  resources :entitle_incentive_details

  resources :entitle_discounts

  resources :entitle_incentives

  devise_for :users

  get "home/index"

   match 'home/reference_categories' => 'home#reference_categories'
   match '/entitles_incentive_detail/:id' => 'home#entitles_incentive_detail',:via => [:get, :post]
   match '/entitles_discount_detail/:id' => 'home#entitles_discount_detail',:via => [:get, :post]

   root :to => 'home#index'

end

app/models/entitle_discount_detail.rb
class EntitleDiscountDetail < ActiveRecord::Base
  attr_accessible :address, :contact_no, :contact_person, :dept, :designation, :dob, :entitle_discount_id, :name, :rate, :ref_code, :specialize, :tax_pan

  belongs_to :entitle_discount

  after_create :save_ref_code

  def save_ref_code
   puts "!!!!"
   
   if self.entitle_discount.ref_type == "Medicine Store"
    @a = Time.now
    @a = SecureRandom.urlsafe_base64(3)
    @code = "MED010" + @a
   end
   
   self.update_attribute(:ref_code,@code)
  end
end

app/controllers/entitle_discount_details_controller.rb
class EntitleDiscountDetailsController < ApplicationController
  before_filter :set_entitle_discount_detail, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @entitle_discount_details = EntitleDiscountDetail.all
    respond_with(@entitle_discount_details)
  end

  def show
    respond_with(@entitle_discount_detail)
  end

  def new
    @entitle_discount_detail = EntitleDiscountDetail.new
    respond_with(@entitle_discount_detail)
  end

  def edit
  end

  def create
    @entitle_discount_detail = EntitleDiscountDetail.new(params[:entitle_discount_detail])
    @entitle_discount_detail.save
    respond_with(@entitle_discount_detail)
  end

  def update
    @entitle_discount_detail.update_attributes(params[:entitle_discount_detail])
    respond_with(@entitle_discount_detail)
  end

  def destroy
    @entitle_discount_detail.destroy
    respond_with(@entitle_discount_detail)
  end

  private
    def set_entitle_discount_detail
      @entitle_discount_detail = EntitleDiscountDetail.find(params[:id])
    end
end

app/helpers/entitle_discount_details_helper.rb
module EntitleDiscountDetailsHelper
end

app/views/entitle_discount_details/_form.html.erb
<%= form_for(@entitle_discount_detail) do |f| %>
 <%= f.hidden_field :entitle_discount_id,:value=>params[:ref_type_id] %>
  <% if @entitle_discount_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entitle_discount_detail.errors.count, "error") %> prohibited this entitle_discount_detail from being saved:</h2>

      <ul>
      <% @entitle_discount_detail.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :contact_no %><br />
    <%= f.text_field :contact_no %>
  </div>
  <div class="field">
    <%= f.label :tax_pan %><br />
    <%= f.text_field :tax_pan %>
  </div>
  <div class="field">
    <%= f.label :specialize %><br />
    <%= f.text_field :specialize %>
  </div>
  <div class="field">
    <%= f.label :contact_person %><br />
    <%= f.text_field :contact_person %>
  </div>
  <div class="field">
    <%= f.label :dept %><br />
    <%= f.text_field :dept %>
  </div>
  <div class="field">
    <%= f.label :designation %><br />
    <%= f.text_field :designation %>
  </div>
  <div class="field">
    <%= f.label :dob %><br />
    <%= f.text_field :dob %>
  </div>
  <div class="field">
    <%= f.label :rate %><br />
    <%= f.number_field :rate %>
  </div>
  
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entitle_discount_details/edit.html.erb
<h1>Editing entitle_discount_detail</h1>

<%= render 'form' %>

<%= link_to 'Show', @entitle_discount_detail %> |
<%= link_to 'Back', entitle_discount_details_path %>

app/views/entitle_discount_details/index.html.erb
<h1>Listing entitle_discount_details</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Contact no</th>
    <th>Tax pan</th>
    <th>Specialize</th>
    <th>Contact person</th>
    <th>Dept</th>
    <th>Designation</th>
    <th>Dob</th>
    <th>Rate</th>
    <th>Ref code</th>
    <th>Entitle discount</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @entitle_discount_details.each do |entitle_discount_detail| %>
  <tr>
    <td><%= entitle_discount_detail.name %></td>
    <td><%= entitle_discount_detail.address %></td>
    <td><%= entitle_discount_detail.contact_no %></td>
    <td><%= entitle_discount_detail.tax_pan %></td>
    <td><%= entitle_discount_detail.specialize %></td>
    <td><%= entitle_discount_detail.contact_person %></td>
    <td><%= entitle_discount_detail.dept %></td>
    <td><%= entitle_discount_detail.designation %></td>
    <td><%= entitle_discount_detail.dob %></td>
    <td><%= entitle_discount_detail.rate %></td>
    <td><%= entitle_discount_detail.ref_code %></td>
    <td><%= entitle_discount_detail.entitle_discount_id %></td>
    <td><%= link_to 'Show', entitle_discount_detail %></td>
    <td><%= link_to 'Edit', edit_entitle_discount_detail_path(entitle_discount_detail) %></td>
    <td><%= link_to 'Destroy', entitle_discount_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Entitle discount detail', new_entitle_discount_detail_path %>

app/views/entitle_discount_details/new.html.erb
<h1>New entitle_discount_detail</h1>

<%= render 'form' %>

<%= link_to 'Back', entitle_discount_details_path %>

app/views/entitle_discount_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @entitle_discount_detail.name %>
</p>

<p>
  <b>Address:</b>
  <%= @entitle_discount_detail.address %>
</p>

<p>
  <b>Contact no:</b>
  <%= @entitle_discount_detail.contact_no %>
</p>

<p>
  <b>Tax pan:</b>
  <%= @entitle_discount_detail.tax_pan %>
</p>

<p>
  <b>Specialize:</b>
  <%= @entitle_discount_detail.specialize %>
</p>

<p>
  <b>Contact person:</b>
  <%= @entitle_discount_detail.contact_person %>
</p>

<p>
  <b>Dept:</b>
  <%= @entitle_discount_detail.dept %>
</p>

<p>
  <b>Designation:</b>
  <%= @entitle_discount_detail.designation %>
</p>

<p>
  <b>Dob:</b>
  <%= @entitle_discount_detail.dob %>
</p>

<p>
  <b>Rate:</b>
  <%= @entitle_discount_detail.rate %>
</p>

<p>
  <b>Ref code:</b>
  <%= @entitle_discount_detail.ref_code %>
</p>

<p>
  <b>Entitle discount:</b>
  <%= @entitle_discount_detail.entitle_discount_id %>
</p>


<%= link_to 'Edit', edit_entitle_discount_detail_path(@entitle_discount_detail) %> |
<%= link_to 'Back', entitle_discount_details_path %>